language: csharp
sudo: required
dist: xenial
mono: none
dotnet: 2.2.103
install:
- dotnet restore
cache:
  directories:
    - node_modules
script:
- dotnet build
- dotnet test Leagueen.Tests.Unit/Leagueen.Tests.Unit.csproj